/**
 * Render the AUR PKGBUILD and .SRCINFO for one release.
 *
 *   bun scripts/render-aur.ts --version 0.2.0 --sha256 <hex> --out aur
 *
 * The sha256 is of GitHub's tag tarball, which the release workflow downloads
 * and hashes. .SRCINFO is written directly because the Ubuntu runner has no
 * makepkg; `makepkg --printsrcinfo` on Arch produces the same file.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

export const pkgname = "kiln-agents";
const pkgdesc = "Vim-style overview of every Claude, Codex and Pi session on the machine";
const url = "https://github.com/cjber/kiln";
const depends = ["bun", "tmux", "fzf"];
const optdepends = [
  "libnotify: desktop notifications when agent turns finish",
  "zoxide: rank the directories offered for new sessions",
  "kitty: jump to agents running in other kitty windows",
  "claude-code: Claude sessions",
  "openai-codex: Codex sessions",
];

const quoted = (items: readonly string[]) => items.map((item) => `'${item}'`).join(" ");

function pkgbuild(version: string, sha256: string): string {
  return `# Maintainer: cjber <cjberragan at gmail dot com>
# Generated by ${url}/blob/main/scripts/render-aur.ts; edits are overwritten on the next release.
pkgname=${pkgname}
pkgver=${version}
pkgrel=1
pkgdesc="${pkgdesc}"
arch=('x86_64' 'aarch64')
url="${url}"
license=('MIT')
depends=(${quoted(depends)})
optdepends=(${quoted(optdepends)})
provides=('kiln')
# The AUR's \`kiln\` is an unrelated static site generator that also installs /usr/bin/kiln.
conflicts=('kiln' 'kiln-agents-bin')
options=('!strip')
source=("\${pkgname}-\${pkgver}.tar.gz::${url}/archive/refs/tags/v\${pkgver}.tar.gz")
sha256sums=('${sha256}')

build() {
  cd "kiln-\${pkgver}"
  bun install --frozen-lockfile --production
}

package() {
  cd "kiln-\${pkgver}"
  install -d "\${pkgdir}/usr/lib/kiln" "\${pkgdir}/usr/bin"
  cp -a bin src extensions bundled-skills node_modules package.json tmux.conf "\${pkgdir}/usr/lib/kiln/"
  ln -s /usr/lib/kiln/bin/kiln "\${pkgdir}/usr/bin/kiln"
  install -Dm644 LICENSE "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
  install -Dm644 README.md "\${pkgdir}/usr/share/doc/\${pkgname}/README.md"
}
`;
}

function srcinfo(version: string, sha256: string): string {
  const lines = [
    `pkgbase = ${pkgname}`,
    `\tpkgdesc = ${pkgdesc}`,
    `\tpkgver = ${version}`,
    "\tpkgrel = 1",
    `\turl = ${url}`,
    "\tarch = x86_64",
    "\tarch = aarch64",
    "\tlicense = MIT",
    ...depends.map((item) => `\tdepends = ${item}`),
    ...optdepends.map((item) => `\toptdepends = ${item}`),
    "\tprovides = kiln",
    "\tconflicts = kiln",
    "\tconflicts = kiln-agents-bin",
    "\toptions = !strip",
    `\tsource = ${pkgname}-${version}.tar.gz::${url}/archive/refs/tags/v${version}.tar.gz`,
    `\tsha256sums = ${sha256}`,
    "",
    `pkgname = ${pkgname}`,
  ];
  return `${lines.join("\n")}\n`;
}

function binaryPackage(version: string, sha256: string, x64: string, arm64: string): { build: string; info: string } {
  const name = "kiln-agents-bin";
  const binaryDepends = depends.filter((item) => item !== "bun");
  const build = `# Maintainer: cjber <cjberragan at gmail dot com>
pkgname=${name}
pkgver=${version}
pkgrel=1
pkgdesc="${pkgdesc}"
arch=('x86_64' 'aarch64')
url="${url}"
license=('MIT')
depends=(${quoted(binaryDepends)})
optdepends=(${quoted(optdepends)})
provides=('kiln' 'kiln-agents')
conflicts=('kiln' 'kiln-agents')
options=('!strip')
source=("kiln-\${pkgver}.tar.gz::${url}/archive/refs/tags/v\${pkgver}.tar.gz")
sha256sums=('${sha256}')
source_x86_64=("kiln-linux-x64-\${pkgver}::${url}/releases/download/v\${pkgver}/kiln-linux-x64")
sha256sums_x86_64=('${x64}')
source_aarch64=("kiln-linux-arm64-\${pkgver}::${url}/releases/download/v\${pkgver}/kiln-linux-arm64")
sha256sums_aarch64=('${arm64}')

package() {
  local binary=kiln-linux-x64
  if [[ "$CARCH" == aarch64 ]]; then binary=kiln-linux-arm64; fi
  install -Dm755 "$binary-\${pkgver}" "\${pkgdir}/usr/bin/kiln"
  install -Dm644 "kiln-\${pkgver}/LICENSE" "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
  install -Dm644 "kiln-\${pkgver}/README.md" "\${pkgdir}/usr/share/doc/\${pkgname}/README.md"
}
`;
  const info = [
    `pkgbase = ${name}`,
    `\tpkgdesc = ${pkgdesc}`,
    `\tpkgver = ${version}`,
    "\tpkgrel = 1",
    `\turl = ${url}`,
    "\tarch = x86_64",
    "\tarch = aarch64",
    "\tlicense = MIT",
    ...binaryDepends.map((item) => `\tdepends = ${item}`),
    ...optdepends.map((item) => `\toptdepends = ${item}`),
    "\tprovides = kiln",
    "\tprovides = kiln-agents",
    "\tconflicts = kiln",
    "\tconflicts = kiln-agents",
    "\toptions = !strip",
    `\tsource = kiln-${version}.tar.gz::${url}/archive/refs/tags/v${version}.tar.gz`,
    `\tsha256sums = ${sha256}`,
    `\tsource_x86_64 = kiln-linux-x64-${version}::${url}/releases/download/v${version}/kiln-linux-x64`,
    `\tsha256sums_x86_64 = ${x64}`,
    `\tsource_aarch64 = kiln-linux-arm64-${version}::${url}/releases/download/v${version}/kiln-linux-arm64`,
    `\tsha256sums_aarch64 = ${arm64}`,
    "",
    `pkgname = ${name}`,
    "",
  ].join("\n");
  return { build, info };
}

if (import.meta.main) {
  const { values } = parseArgs({
    options: {
      version: { type: "string" },
      sha256: { type: "string" },
      out: { type: "string" },
      "bin-x64-sha256": { type: "string" },
      "bin-arm64-sha256": { type: "string" },
    },
  });
  const { version, sha256, out } = values;
  if (!version || !/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`--version must be X.Y.Z, got ${version}`);
  if (!sha256 || !/^[0-9a-f]{64}$/.test(sha256)) throw new Error("--sha256 must be a 64-character hex digest");
  if (!out) throw new Error("--out is required");
  const x64 = values["bin-x64-sha256"];
  const arm64 = values["bin-arm64-sha256"];
  if (x64 || arm64) {
    if (!x64 || !arm64 || ![x64, arm64].every((hash) => /^[0-9a-f]{64}$/.test(hash)))
      throw new Error("both binary sha256 digests must be 64-character hex digests");
    const binary = binaryPackage(version, sha256, x64, arm64);
    mkdirSync(join(out, "bin"), { recursive: true });
    writeFileSync(join(out, "bin", "PKGBUILD"), binary.build);
    writeFileSync(join(out, "bin", ".SRCINFO"), binary.info);
  }
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, "PKGBUILD"), pkgbuild(version, sha256));
  writeFileSync(join(out, ".SRCINFO"), srcinfo(version, sha256));
}
