/**
 * Render the AUR PKGBUILD and .SRCINFO for one release.
 *
 *   bun scripts/render-aur.ts --version 0.2.0 --sha256 <hex> --out aur
 *
 * The sha256 is of GitHub's tag tarball, which the release workflow downloads
 * and hashes. .SRCINFO is written directly because the Ubuntu runner has no
 * makepkg; `makepkg --printsrcinfo` on Arch produces the same file.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

export const pkgname = "kiln-agents";
const pkgdesc = "Vim-style overview of every Claude, Codex and Pi session on the machine";
const url = "https://github.com/cjber/kiln";
const depends = ["bun", "tmux", "fzf"];
const optdepends = [
  "zoxide: rank the directories offered for new sessions",
  "kitty: jump to agents running in other kitty windows",
  "claude-code: Claude sessions",
  "openai-codex: Codex sessions",
];

const quoted = (items: readonly string[]) => items.map((item) => `'${item}'`).join(" ");

function pkgbuild(version: string, sha256: string): string {
  return `# Maintainer: cjber <cjberragan at gmail dot com>
# Generated by ${url}/blob/main/scripts/render-aur.ts; edits are overwritten on the next release.
pkgname=${pkgname}
pkgver=${version}
pkgrel=1
pkgdesc="${pkgdesc}"
arch=('x86_64' 'aarch64')
url="${url}"
license=('MIT')
depends=(${quoted(depends)})
optdepends=(${quoted(optdepends)})
provides=('kiln')
# The AUR's \`kiln\` is an unrelated static site generator that also installs /usr/bin/kiln.
conflicts=('kiln')
options=('!strip')
source=("\${pkgname}-\${pkgver}.tar.gz::${url}/archive/refs/tags/v\${pkgver}.tar.gz")
sha256sums=('${sha256}')

build() {
  cd "kiln-\${pkgver}"
  bun install --frozen-lockfile --production
}

package() {
  cd "kiln-\${pkgver}"
  install -d "\${pkgdir}/usr/lib/kiln" "\${pkgdir}/usr/bin"
  cp -a bin src node_modules package.json tmux.conf "\${pkgdir}/usr/lib/kiln/"
  ln -s /usr/lib/kiln/bin/kiln "\${pkgdir}/usr/bin/kiln"
  install -Dm644 LICENSE "\${pkgdir}/usr/share/licenses/\${pkgname}/LICENSE"
  install -Dm644 README.md "\${pkgdir}/usr/share/doc/\${pkgname}/README.md"
}
`;
}

function srcinfo(version: string, sha256: string): string {
  const lines = [
    `pkgbase = ${pkgname}`,
    `\tpkgdesc = ${pkgdesc}`,
    `\tpkgver = ${version}`,
    "\tpkgrel = 1",
    `\turl = ${url}`,
    "\tarch = x86_64",
    "\tarch = aarch64",
    "\tlicense = MIT",
    ...depends.map((item) => `\tdepends = ${item}`),
    ...optdepends.map((item) => `\toptdepends = ${item}`),
    "\tprovides = kiln",
    "\tconflicts = kiln",
    "\toptions = !strip",
    `\tsource = ${pkgname}-${version}.tar.gz::${url}/archive/refs/tags/v${version}.tar.gz`,
    `\tsha256sums = ${sha256}`,
    "",
    `pkgname = ${pkgname}`,
  ];
  return `${lines.join("\n")}\n`;
}

if (import.meta.main) {
  const { values } = parseArgs({
    options: { version: { type: "string" }, sha256: { type: "string" }, out: { type: "string" } },
  });
  const { version, sha256, out } = values;
  if (!version || !/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`--version must be X.Y.Z, got ${version}`);
  if (!sha256 || !/^[0-9a-f]{64}$/.test(sha256)) throw new Error("--sha256 must be a 64-character hex digest");
  if (!out) throw new Error("--out is required");
  mkdirSync(out, { recursive: true });
  writeFileSync(join(out, "PKGBUILD"), pkgbuild(version, sha256));
  writeFileSync(join(out, ".SRCINFO"), srcinfo(version, sha256));
}
